# Generated by Django 5.0.3 on 2024-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absent',
            name='response_content',
            field=models.TextField(blank=True),
        ),
    ]
