# Generated by Django 5.0.3 on 2024-11-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absent', '0004_alter_absent_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absent',
            options={'ordering': ['-create_time']},
        ),
    ]
